### ISSUE TITLE
Some bugs?

### ISSUE THREAD

**Issue by geotyper** [hschwane/mpmDemo#2]
Try to start this demo, all compile and works, but particle(that water) began to disappears from screen and not collide with sand.
![image](https://user-images.githubusercontent.com/30755433/98372043-342f8700-204e-11eb-8f1d-8314322ecbd1.png)

Can it be fixed?

**Comment by hschwane** [comment]
Yes, something is broken for sure. Unfortunately I could never actually make it work and gave up on it as I had to work on other things. It was meant to be a weekend project... 

If you can fix it I would gladly accept a pull request.

Edit: also sorry for the inconvenience. I did not think anyone would actually try it out. I will add a note to the readme.
